### ISSUE TITLE
Add documentation about CORS

### ISSUE THREAD

**Issue by mraible** [ruddell/generator-jhipster-react-native#247]
**Describe the bug**

With JHipster 7, not all URLs are allowed by default anymore. The default CORS setting is only configured for Ionic. From `application-dev.yml`:

```
jhipster:
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100'
```

Maybe we should change it to include the React Native blueprint?

```
allowed-origins: 'http://localhost:8100,http://localhost:19006'
```

**Instructions To reproduce**

Create a JHipster app, create a React Native app, try to log in in a browser.

**JHipster app's `.yo-rc.json`**

```json
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "clientFramework": "react",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": true,
    "withAdminUi": true,
    "baseName": "HealthPoints",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "es"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["cypress"],
    "websocket": false,
    "applicationType": "monolith",
    "reactive": true,
    "packageName": "com.okta.developer",
    "packageFolder": "com/okta/developer",
    "nativeLanguage": "en",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": ["Points", "BloodPressure", "Weight", "Preferences"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1615862250727,
    "lastLiquibaseTimestamp": 1615862490000
  }
}
```

**Entity JDL or JSON files**

**Versions (please complete the following information):**

- JHipster React Native Version: latest
- `jhipster info` output: `main` branch

**Comment by mraible** [comment]
I did find documentation in the TIPS section of the generated README. Thanks!

I was able to configure my React Native app to work with Okta, but I'm unable to logout. It gives me a CORS error, even though I have the following in my JHipster app.

```yaml
jhipster:
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:19006'
```

I'm able to log in, but when I logout, I see a CORS error in my browser's console.

<img width="1064" alt="Screen Shot 2021-03-16 at 12 24 33 AM" src="https://user-images.githubusercontent.com/17892/111265396-a57bd980-85ee-11eb-9d55-a6dfa95ba293.png">

If I try to login again, it logs me in without prompting me for my credentials.

<img width="1064" alt="Screen Shot 2021-03-16 at 12 24 41 AM" src="https://user-images.githubusercontent.com/17892/111265449-b75d7c80-85ee-11eb-9992-ae3a2ff67c63.png">

Here's the app I created using the Okta CLI.

<img width="749" alt="Screen Shot 2021-03-16 at 12 25 45 AM" src="https://user-images.githubusercontent.com/17892/111265473-c2181180-85ee-11eb-900c-5088d17f31ac.png">
